name: im_themed
description: package for parsing flutter theme from json, with support for css like syntax
version: 0.0.5
repository: https://github.com/i-m-cyber/im_themed

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # csslib: ^1.0.0
  # google_fonts: ^5.0.0
  json_annotation: ^4.8.1
  source_span: ^1.9.1
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
